#docker run -u root --rm -d -p 8080:8080 -p 50000:50000 -v jenkins-data:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock --name jenkins-blueocean jenkinsci/blueocean
version: '3'

services:
  jenkins-blueocean:
    image: jenkinsci/blueocean
    container_name: jenkins-blueocean
    user: root
    privileged: true
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  registry:
    image: registry
    container_name: registry
    restart: always
    ports:
      - 5000:5000
volumes:
    jenkins-data:
